import { Inter,Montserrat } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import Header from '../components/Header'

const inter = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Taxi App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
    <head>
          <link rel="icon" type="image/png" href="logo.png" />
          {/* Замените '/favicon.png' на путь к вашей иконке */}
          {/* Тип иконки (type) должен соответствовать формату вашего изображения */}
        </head>
      <body className={inter.className}>
        <Header/>
        {children}
        </body>
    </html>
    </ClerkProvider>
  )
}